In [1]:
import pandas as pd
import addition_functions as af

url = '/Users/k.yukhlina/IronHack/Week_4/Day_1/archive/airnb.csv'
airbnb_df = pd.read_csv(url, encoding='utf8')
airbnb_df

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed
...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed
949,Room in Kissimmee,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed
950,Guesthouse in San Antonio,Casa Alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds
951,Apartment in Englewood,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96 (318),4 beds
952,Room in Long Beach,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds

In [2]:
airbnb_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   953 non-null    str
 1   Detail                  953 non-null    str
 2   Date                    953 non-null    str
 3   Price(in dollar)        953 non-null    str
 4   Offer price(in dollar)  166 non-null    str
 5   Review and rating       947 non-null    str
 6   Number of bed           953 non-null    str
dtypes: str(7)
memory usage: 52.2 KB

**Problem #1** We have 'Price(in dollar)' and 'Offer price(in dollar)' as a str. If we wanted to count it we need to convert tham into float

**Problem #2** 'Review and rating' is a str too. We need to get float for 'rating' and int for 'amount of answers'

In [3]:
airbnb_df.shape

(953, 7)

In [4]:
airbnb_df.nunique()

Title                     756
Detail                    839
Date                      204
Price(in dollar)          322
Offer price(in dollar)    108
Review and rating         754
Number of bed              33
dtype: int64

I'm trying to make the number of values shorter in "Number of bed"

In [5]:
airbnb_df["Number of bed"].value_counts()

Number of bed
2 beds           221
3 beds           117
1 queen bed      105
1 bed            100
1 king bed        87
4 beds            63
1 double bed      55
2 queen beds      49
2 double beds     24
2 king beds       21
1 sofa bed        19
5 beds            17
6 beds            17
3 queen beds       8
2 single beds      7
9 beds             5
4 double beds      5
3 double beds      5
4 single beds      4
8 beds             4
7 beds             3
2 sofa beds        3
1 bunk bed         3
5 double beds      2
4 sofa beds        1
11 beds            1
22 beds            1
3 king beds        1
4 king beds        1
17 beds            1
4 queen beds       1
13 beds            1
10 beds            1
Name: count, dtype: int64

I cleaned data

In [6]:
airbnb_df["Number of bed"] = af.clear_data(airbnb_df["Number of bed"]) #there is an external function "clear_data" located in external file

But the cleaning doesn't help to decrease amount of categorial values.

**Sugestion:** we can stay it like this

In [7]:
airbnb_df["Number of bed"].value_counts()

Number of bed
2 beds           221
3 beds           117
1 queen bed      105
1 bed            100
1 king bed        87
4 beds            63
1 double bed      55
2 queen beds      49
2 double beds     24
2 king beds       21
1 sofa bed        19
5 beds            17
6 beds            17
3 queen beds       8
2 single beds      7
9 beds             5
4 double beds      5
3 double beds      5
4 single beds      4
8 beds             4
7 beds             3
2 sofa beds        3
1 bunk bed         3
5 double beds      2
4 sofa beds        1
11 beds            1
22 beds            1
3 king beds        1
4 king beds        1
17 beds            1
4 queen beds       1
13 beds            1
10 beds            1
Name: count, dtype: int64

We need to split the column into two

In [8]:
airbnb_df["Review and rating"].value_counts()

Review and rating
New           16
5.0 (11)       6
5.0 (9)        6
5.0 (4)        5
5.0 (13)       5
              ..
4.85 (82)      1
4.9 (300)      1
4.92 (282)     1
4.96 (318)     1
4.85 (97)      1
Name: count, Length: 754, dtype: int64

In addition I decided to make all column names with lower case and with "_" instead of " "

In [24]:
airbnb_df.columns = [(column.lower()).replace(" ","_") for column in airbnb_df.columns]  
airbnb_df

,title,detail,date,price(in_dollar),offer_price(in_dollar),review_and_rating,number_of_bed
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed
...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed
949,Room in Kissimmee,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed
950,Guesthouse in San Antonio,Casa Alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds
951,Apartment in Englewood,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96 (318),4 beds
952,Room in Long Beach,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds

We're splitting data from 'review_and_rating' into 'review_and_rating' and 'amount_of_answeres'

In [46]:
airbnb_df_copy = airbnb_df.copy()
airbnb_df_copy[['review_and_rating', 'amount_of_answeres']] = airbnb_df_copy.review_and_rating.str.split(" ", expand=True)

In [47]:
airbnb_df_copy

,title,detail,date,price(in_dollar),offer_price(in_dollar),review_and_rating,number_of_bed,amount_of_answeres
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85,4 beds,(531)
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77,4 beds,(146)
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91,4 beds,(515)
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94,5 beds,(88)
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99,1 queen bed,(222)
...,...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85,1 king bed,(82)
949,Room in Kissimmee,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9,1 king bed,(300)
950,Guesthouse in San Antonio,Casa Alexander,May 1 - 6,73.00,NaN,4.92,5 beds,(282)
951,Apartment in Englewood,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96,4 beds,(318)
952,Room in Long Beach,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85,4 beds,(97)

We need to drop "()" from 'amount_of_answeres'

In [44]:
airbnb_df_copy["amount_of_answeres"] = airbnb_df_copy["amount_of_answeres"].str.replace(r'[()]', '', regex=True)

In [45]:
airbnb_df_copy

,title,detail,date,price(in_dollar),offer_price(in_dollar),review_and_rating,number_of_bed,amount_of_answeres
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85,4 beds,531
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77,4 beds,146
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91,4 beds,515
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94,5 beds,88
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99,1 queen bed,222
...,...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85,1 king bed,82
949,Room in Kissimmee,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9,1 king bed,300
950,Guesthouse in San Antonio,Casa Alexander,May 1 - 6,73.00,NaN,4.92,5 beds,282
951,Apartment in Englewood,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96,4 beds,318
952,Room in Long Beach,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85,4 beds,97

We need to cast 'review_and_rating' into float and 'amount_of_answeres' into int. But first we need to find NaNs

In [53]:
airbnb_df_copy.isna().any()

title                     False
detail                    False
date                      False
price(in_dollar)          False
offer_price(in_dollar)     True
review_and_rating          True
number_of_bed             False
amount_of_answeres         True
dtype: bool

We have NaNs 'review_and_rating' and 'amount_of_answeres'. So, we need to clear them before casting (in progress...)

In [56]:
airbnb_df_copy["title"].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
948    False
949    False
950    False
951    False
952    False
Name: title, Length: 953, dtype: bool