In [8]:
from google.colab import drive
import pandas as pd

# Read the CSV file from drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Airbnb_Data/airnb.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Airbnb_Data/airnb_desert.csv', encoding='latin1')
df3 = pd.read_csv('/content/drive/MyDrive/Airbnb_Data/airnb_luxe.csv', encoding='latin1')

display(df.head())
display(df2.head())
display(df3.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed

,Desert name,Date,Price(In dollar),Details,Rating
0,"Mhamid, Morocco",May 1  29,479.00,Near Sahara Desert,4.79
1,"Aqaba City, Jordan",May 1  29,"2,168.00",Near Arabian Desert,4.92
2,"Tamesluht, Morocco",May 1  29,"17,752.00","9,404 kilometers away",4.95
3,"Al Bairat, Egypt",May 1  29,"1,982.00",Near Sahara Desert,4.88
4,"Tamesluht, Morocco",May 1  29,"17,752.00","9,404 kilometers away",4.87

             Luxe name        Date Price(In dollar)               Distance
0  Koh Samui, Thailand  May 1  29        89,600.00  1,880 kilometers away
1  Koh Samui, Thailand  May 1  29        78,459.00  1,880 kilometers away
2  Koh Samui, Thailand  May 1  29        53,200.00  1,881 kilometers away
3  Koh Samui, Thailand  May 1  29        35,000.00  1,880 kilometers away
4     Nathon, Thailand  May 1  29        19,656.00  1,872 kilometers away

In [4]:
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   953 non-null    object
 1   Detail                  953 non-null    object
 2   Date                    953 non-null    object
 3   Price(in dollar)        953 non-null    object
 4   Offer price(in dollar)  166 non-null    object
 5   Review and rating       947 non-null    object
 6   Number of bed           953 non-null    object
dtypes: object(7)
memory usage: 52.2+ KB

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
count,953,953,953,953,166,947,953
unique,756,839,204,322,108,754,33
top,"Apartment in Kuala Lumpur, Malaysia",Cozy room 48.5 sq.m @The Astra near Night market,May 1 - 6,111.00,63.00,New,2 beds
freq,7,3,219,13,4,16,221

In [11]:
df.detail = (
    df.Detail
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("*", "_", regex=False)
    .str.replace(r"[^a-z0-9_]", "", regex=True)
)
display (df)

/tmp/ipykernel_545/511648279.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.detail = (

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed
...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed
949,Room in Kissimmee,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed
950,Guesthouse in San Antonio,Casa Alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds
951,Apartment in Englewood,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96 (318),4 beds
952,Room in Long Beach,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds

In [12]:
df["Date"].head(20)

0        Jun 11 - 16
1         Jun 6 - 11
2         Jul 9 - 14
3        Jun 11 - 16
4          Jun 4 - 9
5        Jun 21 - 26
6          Jun 4 - 9
7         Jun 8 - 15
8          Jul 3 - 8
9     Jun 26 - Jul 1
10        Sep 4 - 10
11         Jun 1 - 6
12         Jun 1 - 6
13       Sep 11 - 16
14         Jun 1 - 6
15        Sep 8 - 13
16       Jun 11 - 16
17       Jun 18 - 23
18       Aug 20 - 25
19        Jun 9 - 14
Name: Date, dtype: object

In [56]:
import pandas as pd

def title_extractor(df: pd.DataFrame) -> pd.DataFrame:
    temp_df = df.copy()
    temp_df[["Header", "State", "Country"]] = temp_df["Title"].str.split(
        ",", expand=True
    )
    temp_df.drop("Title", inplace=True, axis=1)
    return temp_df

In [57]:
df_extracted = title_extractor(df)
display(df_extracted.head(30))

,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed,Header,State,Country
0,Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds,Chalet in Skykomish,Washington,US
1,The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds,Cabin in Hancock,New York,US
2,The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds,Cabin in West Farmington,Ohio,US
3,*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds,Home in Blue Ridge,Georgia,US
4,Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed,Treehouse in Grandview,Texas,US
5,Casa Tiny near Casa Wabi,Jun 21 - 26,261.00,148.00,4.84 (555),1 double bed,Tiny home in Puerto Escondido,Mexico,None
6,The Beach House. Oceanfront & Sunrise Views!,Jun 4 - 9,607.00,NaN,4.64 (90),2 queen beds,Home in Saco,Maine,US
7,• Cedar Peak • 2 Bedroom Barrier-Free Chalet,Jun 8 - 15,381.00,NaN,5.0 (48),2 beds,Chalet in Grand Étang,Canada,None
8,"Room in apartment, traditional neighborhood",Jul 3 - 8,29.00,NaN,4.84 (58),2 beds,Room in Mexico City,Mexico,None
9,Peacock Tiny House near Las Vegas,Jun 26 - Jul 1,154.00,NaN,4.92 (744),3 beds,Tiny home in Sandy Valley,Nevada,US
10,Hidden Valley’s Guest Suite - explore nature,Sep 4 - 10,207.00,NaN,4.97 (265),2 beds,Guest suite in Huntsville,Canada,None
11,Downey Family Cabin. Barrel Sauna Included!,Jun 1 - 6,162.00,NaN,4.99 (226),2 king beds,Cabin in Nelson,Canada,None
12,Dome in the Desert in Joshua Tree,Jun 1 - 6,268.00,NaN,4.94 (944),1 king bed,Dome in Joshua Tree,California,US
13,Private Barn Studio at Pura Vida Florida Farm,Sep 11 - 16,111.00,NaN,4.95 (417),2 double beds,Barn in Vero Beach,Florida,US
14,Cozy Tiny House Cabin between Burlington and S...,Jun 1 - 6,174.00,NaN,4.97 (372),2 queen beds,Tiny home in Bolton,Vermont,US
15,Peace Cabin - private waterfront forest retreat,Sep 8 - 13,497.00,NaN,4.99 (69),1 king bed,Cabin in Ucluelet,Canada,None
16,14th Homestead Barn Loft,Jun 11 - 16,163.00,NaN,4.9 (289),1 king bed,Barn in Essex,Canada,None
17,"Lagoon Front Hut: Daily Cleaning, Bikes & Kayaks!",Jun 18 - 23,141.00,NaN,4.89 (633),1 king bed,Apartment in Bacalar,Mexico,None
18,The Forestry House - A modern luxury treehouse.,Aug 20 - 25,282.00,417.00,New,1 bed,Treehouse in Travelers Rest,South Carolina,US
19,Underground Hobbit Hole @ Sustainable Ecovillage,Jun 9 - 14,89.00,253.00,4.54 (195),1 bed,Farm stay in Del Norte County,California,US
20,Rainforest Tree House with Hot Springs,Aug 31 - Sep 5,132.00,NaN,4.84 (763),3 beds,Treehouse in San Carlos,Costa Rica,None
21,Tullihas in the Trees Off-Grid Treehouse,Jun 4 - 9,143.00,NaN,4.98 (181),2 beds,Treehouse in Frazeysburg,Ohio,US
22,SECLUDED LAKESIDE CABIN,Jul 23 - 28,463.00,NaN,4.99 (172),3 beds,Cabin in Rodney,Canada,None
23,Fauria Colonial House (Room 3),Jun 21 - 26,29.00,NaN,4.92 (75),1 bed,Room in La Habana,Cuba,None
24,Domeland: Off-grid Adobe Dome near Big Bend,Jul 9 - 14,136.00,NaN,4.95 (863),5 beds,Dome in Terlingua,Texas,US
25,Lake Sutherland Waterfront Cabin w/ Expansive ...,Sep 1 - 6,688.00,NaN,4.82 (83),1 king bed,Home in Port Angeles,Washington,US
26,Luxury Tree House X Magical Romantic Forest! P...,Jun 18 - 23,658.00,NaN,4.91 (142),1 king bed,Treehouse in Fredericksburg,Texas,US
27,Scandinavian-Inspired Tiny Home Experience,Sep 3 - 8,392.00,NaN,4.98 (95),2 beds,Cottage in Harcourt,Canada,None
28,Tiny House Cubo Nube Santa Elena 40 min. Medel...,Jun 17 - 22,67.00,NaN,4.95 (197),1 queen bed,Tiny home in Medellín,Colombia,None
29,Chalet Boutique Saltamontes Santa Elena,Jun 4 - 9,51.00,NaN,4.94 (232),2 beds,Cabin in Medellín,Colombia,None

In [58]:
df_extracted.columns = [(column.lower()).replace(" ","_") for column in df_extracted.columns]
display(df_extracted)

,detail,date,price(in_dollar),offer_price(in_dollar),review_and_rating,number_of_bed,header,state,country
0,Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds,Chalet in Skykomish,Washington,US
1,The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds,Cabin in Hancock,New York,US
2,The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds,Cabin in West Farmington,Ohio,US
3,*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds,Home in Blue Ridge,Georgia,US
4,Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed,Treehouse in Grandview,Texas,US
...,...,...,...,...,...,...,...,...,...
948,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed,Guest suite in Lake Worth,None,None
949,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed,Room in Kissimmee,None,None
950,Casa Alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds,Guesthouse in San Antonio,None,None
951,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96 (318),4 beds,Apartment in Englewood,None,None
952,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds,Room in Long Beach,None,None

In [62]:
df_extracted[['raiting','reviews']] = df_extracted.review_and_rating.str.split(" ", expand=True)
display(df_extracted)

,detail,date,price(in_dollar),offer_price(in_dollar),review_and_rating,number_of_bed,header,state,country,raiting,reviews
0,Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds,Chalet in Skykomish,Washington,US,4.85,(531)
1,The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds,Cabin in Hancock,New York,US,4.77,(146)
2,The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds,Cabin in West Farmington,Ohio,US,4.91,(515)
3,*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds,Home in Blue Ridge,Georgia,US,4.94,(88)
4,Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed,Treehouse in Grandview,Texas,US,4.99,(222)
...,...,...,...,...,...,...,...,...,...,...,...
948,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed,Guest suite in Lake Worth,None,None,4.85,(82)
949,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed,Room in Kissimmee,None,None,4.9,(300)
950,Casa Alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds,Guesthouse in San Antonio,None,None,4.92,(282)
951,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96 (318),4 beds,Apartment in Englewood,None,None,4.96,(318)
952,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds,Room in Long Beach,None,None,4.85,(97)

In [63]:
df_extracted["reviews"] = df_extracted["reviews"].str.replace(r'[()]', '', regex=True)
display(df_extracted)

,detail,date,price(in_dollar),offer_price(in_dollar),review_and_rating,number_of_bed,header,state,country,raiting,reviews
0,Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds,Chalet in Skykomish,Washington,US,4.85,531
1,The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds,Cabin in Hancock,New York,US,4.77,146
2,The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds,Cabin in West Farmington,Ohio,US,4.91,515
3,*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds,Home in Blue Ridge,Georgia,US,4.94,88
4,Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed,Treehouse in Grandview,Texas,US,4.99,222
...,...,...,...,...,...,...,...,...,...,...,...
948,The Garden Suite at the Historic Chateau Bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed,Guest suite in Lake Worth,None,None,4.85,82
949,Private Room in Orlando/Kissimmee (2Twins) T1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed,Room in Kissimmee,None,None,4.9,300
950,Casa Alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds,Guesthouse in San Antonio,None,None,4.92,282
951,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,May 7 - 12,233.00,NaN,4.96 (318),4 beds,Apartment in Englewood,None,None,4.96,318
952,Across the Street from Beach Getaway/Near Conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds,Room in Long Beach,None,None,4.85,97

In [66]:
df_extracted.drop(['detail', 'date','number_of_bed','review_and_rating'], axis=1, inplace=True)
display(df_extracted)
#df_extracted.dropna(subset=['detail', 'date','review_and_rating','number_of_bed','raiting_and_reviews'])

,price(in_dollar),offer_price(in_dollar),header,state,country,raiting,reviews
0,306.00,229.00,Chalet in Skykomish,Washington,US,4.85,531
1,485.00,170.00,Cabin in Hancock,New York,US,4.77,146
2,119.00,522.00,Cabin in West Farmington,Ohio,US,4.91,515
3,192.00,348.00,Home in Blue Ridge,Georgia,US,4.94,88
4,232.00,196.00,Treehouse in Grandview,Texas,US,4.99,222
...,...,...,...,...,...,...,...
948,141.00,NaN,Guest suite in Lake Worth,None,None,4.85,82
949,43.00,NaN,Room in Kissimmee,None,None,4.9,300
950,73.00,NaN,Guesthouse in San Antonio,None,None,4.92,282
951,233.00,NaN,Apartment in Englewood,None,None,4.96,318
952,106.00,NaN,Room in Long Beach,None,None,4.85,97

In [ ]:
import numpy as np
import seaborn as sns
from statistics import mode
import matplotlib.pyplot as plt


season_country_df = df_extracted(['Clean_country','Season'])['Date'].agg(['count']).reset_index().pivot(index='Season', columns='Clean_country', values='count')

season_country_new_df = season_country_df.unstack("Season").reset_index(level=[0, 1]).copy()
season_order = {"Winter": 1, "Spring": 2, "Summer": 3, "Autum": 4}
s = season_country_new_df.sort_values(by=["Clean_country","Season"], key=lambda x: x.map(season_order))
s.columns = ["Country", "Season", "Number_of_Attacks"]
display(s)
sns.barplot(data=s, x="Season", y="Number_of_Attacks", hue="Country");
#plt.save_fig("season_country.png")
plt.show()
#season_country_df.plot(figsize=(8, 4))
#plt.show()